apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xbt5aizfg-python-gitops
  description: This is GitOps manifest for xbt5aizfg-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=xbt5aizfg-python
    backstage.io/kubernetes-id: xbt5aizfg-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: xbt5aizfg-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:xbt5aizfg-python
