apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xbt5aizfg-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xbt5aizfg-python 
  name: xbt5aizfg-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xbt5aizfg-python 
