apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xbt5aizfg-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-118057e458.3jtw.p3.openshiftapps.com/rhtap/rhtap-qe-python:d3e469e9f8f2af7de0e4f72ed7687a1f0e44ac16@sha256:336a4400ce92a3a4e064c750687c122f795173b6af38e51b8070af17eaba363b
          name: container-image
